export const EXPENSE_CATEGORIES = [
  'Travel and Transportation',
  "Office and Facilities",
  'Office Supplies and Equipment',
  'Payroll and Employee Costs',
  'Sales and Marketing',
  'Professional Services',
  'Insurance and Compliance',
  'Others',
] as const;
export type ExpenseCategory = (typeof EXPENSE_CATEGORIES)[number];

// Payment methods are a shared, admin-managed catalog (see the payment_methods
// table / catalogRoutes.ts) — same one used by orders, not an expense-specific enum.

export const RECURRENCE_FREQUENCIES = ['daily', 'weekly', 'monthly'] as const;
export type RecurrenceFrequency = (typeof RECURRENCE_FREQUENCIES)[number];

// Which system, if any, auto-generated an expense. Derived once in expenseStore.ts's
// mapRowToExpense from whichever marker column is set, rather than checked ad hoc at each of the
// several call sites (routes/expenses.ts's PUT/DELETE guards, the Expenses table's Auto badge,
// the edit dialog's locked-field banner) so a future second source doesn't require touching all
// of them individually.
export type ExpenseAutoSource = 'commission_release';

export interface Expense {
  id: string;
  date: string;
  amount: number;
  category: string;
  paymentMethod: string;
  notes: string;
  createdBy: string | null;
  createdByName: string;
  recurringExpenseId: string | null;
  // Set only on expenses auto-generated by a commission release (see commissionStore.ts) -- the
  // order ids whose released commission this expense covers. Null on every manually-entered
  // expense. Amount/category/date on these are locked in routes/expenses.ts; only Release/Undo
  // Release on the Commissions page can change them, to keep this array and the amount in sync.
  commissionOrderIds: string[] | null;
  autoGeneratedSource: ExpenseAutoSource | null;
  createdAt: string;
  updatedAt: string;
}

export type ExpenseInput = Partial<
  Omit<
    Expense,
    | 'id'
    | 'createdBy'
    | 'createdByName'
    | 'recurringExpenseId'
    | 'commissionOrderIds'
    | 'autoGeneratedSource'
    | 'createdAt'
    | 'updatedAt'
  >
>;

export interface RecurringExpense {
  id: string;
  amount: number;
  category: string;
  paymentMethod: string;
  notes: string;
  frequency: RecurrenceFrequency;
  startDate: string;
  nextRunDate: string;
  active: boolean;
  createdBy: string | null;
  createdByName: string;
  createdAt: string;
  updatedAt: string;
}

export type RecurringExpenseInput = Partial<
  Omit<RecurringExpense, 'id' | 'nextRunDate' | 'createdBy' | 'createdByName' | 'createdAt' | 'updatedAt'>
>;
