-- Marks an expense as auto-generated by a commission release and lists exactly which orders'
-- commission it covers. Null on every ordinary, manually-entered expense.
alter table expenses add column if not exists commission_order_ids uuid[];

-- list_expenses(): return commission_order_ids alongside the other expense fields so the
-- frontend can lock Amount/Category/Date and disable Delete for these rows. Parameter list is
-- unchanged (row-shape addition only), same as list_users' commission_rate addition.
create or replace function list_expenses(
  p_search text default null,
  p_category text default null,
  p_payment_method text default null,
  p_date_from date default null,
  p_date_to date default null,
  p_created_by uuid default null,
  p_limit int default 10,
  p_offset int default 0,
  p_sort_by text default 'date',
  p_sort_dir text default 'desc'
)
returns jsonb
language sql
stable
as $$
  with filtered as (
    select e.*
    from expenses e
    where
      (p_search is null or p_search = '' or
        e.notes ilike '%' || p_search || '%' or
        e.category ilike '%' || p_search || '%')
      and (p_category is null or p_category = '' or e.category = p_category)
      and (p_payment_method is null or p_payment_method = '' or e.payment_method = p_payment_method)
      and (p_date_from is null or e.date >= p_date_from)
      and (p_date_to is null or e.date <= p_date_to)
      and (p_created_by is null or e.created_by = p_created_by)
  ),
  sorted as (
    select
      f.*,
      case p_sort_by when 'category' then f.category end as sort_text,
      case p_sort_by when 'amount' then f.amount end as sort_num
    from filtered f
  ),
  paged as (
    select *
    from sorted
    order by
      case when p_sort_dir = 'asc' then sort_text end asc,
      case when p_sort_dir = 'desc' then sort_text end desc,
      case when p_sort_dir = 'asc' then sort_num end asc,
      case when p_sort_dir = 'desc' then sort_num end desc,
      case when p_sort_by = 'date' and p_sort_dir = 'asc' then date end asc,
      case when p_sort_by = 'date' and p_sort_dir = 'desc' then date end desc,
      case when p_sort_by = 'created_at' and p_sort_dir = 'asc' then created_at end asc,
      case when p_sort_by = 'created_at' and p_sort_dir = 'desc' then created_at end desc,
      date desc,
      created_at desc
    limit p_limit offset p_offset
  )
  select jsonb_build_object(
    'rows', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', p.id,
        'date', p.date,
        'amount', p.amount,
        'category', p.category,
        'payment_method', p.payment_method,
        'notes', p.notes,
        'created_by', p.created_by,
        'created_by_name', coalesce(nullif(trim(coalesce(u.first_name, '') || ' ' || coalesce(u.last_name, '')), ''), ''),
        'recurring_expense_id', p.recurring_expense_id,
        'commission_order_ids', p.commission_order_ids,
        'created_at', p.created_at,
        'updated_at', p.updated_at
      ) order by
        case when p_sort_dir = 'asc' then p.sort_text end asc,
        case when p_sort_dir = 'desc' then p.sort_text end desc,
        case when p_sort_dir = 'asc' then p.sort_num end asc,
        case when p_sort_dir = 'desc' then p.sort_num end desc,
        case when p_sort_by = 'date' and p_sort_dir = 'asc' then p.date end asc,
        case when p_sort_by = 'date' and p_sort_dir = 'desc' then p.date end desc,
        case when p_sort_by = 'created_at' and p_sort_dir = 'asc' then p.created_at end asc,
        case when p_sort_by = 'created_at' and p_sort_dir = 'desc' then p.created_at end desc,
        p.date desc,
        p.created_at desc)
      from paged p
      left join users u on u.id = p.created_by
    ), '[]'::jsonb),
    'total', (select count(*) from filtered)
  );
$$;

-- Lets unrelease find and adjust/delete the expense an order's commission was folded into.
alter table orders add column if not exists commission_expense_id uuid references expenses(id) on delete set null;

-- release_commission_orders(): now plpgsql (was sql) so it can group the batch of orders being
-- released by staff member and create one expense per staff group in the same transaction --
-- "Commission release -- Arwin Manalang (3 orders)" rather than one expense row per order.
-- Snapshots each order's commission amount once (via the temp table) before any writes, same
-- race-avoidance as before. Idempotent: only touches paid, not-yet-released orders.
create or replace function release_commission_orders(p_order_ids uuid[], p_actor_id uuid)
returns jsonb
language plpgsql
as $$
declare
  v_group record;
  v_expense_id uuid;
  v_released_ids uuid[] := '{}';
begin
  create temporary table tmp_released_orders on commit drop as
  select o.id, o.layout_by, o.layout_fee * (u.commission_rate / 100.0) as amount
  from orders o
  join users u on u.id = o.layout_by
  where o.id = any(p_order_ids)
    and o.payment_status = 'paid'
    and o.commission_released_at is null;

  if not exists (select 1 from tmp_released_orders) then
    return '[]'::jsonb;
  end if;

  for v_group in
    select layout_by, sum(amount) as total_amount, array_agg(id) as order_ids, count(*) as order_count
    from tmp_released_orders
    group by layout_by
  loop
    insert into expenses (id, date, amount, category, payment_method, notes, created_by, commission_order_ids)
    values (
      gen_random_uuid(),
      current_date,
      v_group.total_amount,
      'Payroll and Employee Costs',
      'Cash',
      'Commission release — '
        || (select trim(coalesce(first_name, '') || ' ' || coalesce(last_name, '')) from users where id = v_group.layout_by)
        || ' (' || v_group.order_count || ' order' || case when v_group.order_count = 1 then '' else 's' end || ')',
      p_actor_id,
      v_group.order_ids
    )
    returning id into v_expense_id;

    update orders o
    set commission_released_at = now(),
        commission_released_by = p_actor_id,
        commission_released_amount = tro.amount,
        commission_expense_id = v_expense_id
    from tmp_released_orders tro
    where o.id = tro.id and tro.layout_by = v_group.layout_by;

    v_released_ids := v_released_ids || v_group.order_ids;
  end loop;

  return to_jsonb(v_released_ids);
end;
$$;

-- unrelease_commission_orders(): replaces the plain orders-only update previously issued from
-- commissionStore.ts -- now needs to also shrink or delete the expense(s) a release folded these
-- orders into, so it's an RPC rather than a direct client-side update. For each expense touched,
-- subtracts the unreleased orders' snapshotted amounts and removes their ids from
-- commission_order_ids; deletes the expense entirely once no order ids remain on it.
create or replace function unrelease_commission_orders(p_order_ids uuid[])
returns jsonb
language plpgsql
as $$
declare
  v_expense_id uuid;
  v_unreleased_ids uuid[];
begin
  create temporary table tmp_unreleased_orders on commit drop as
  select o.id, o.commission_expense_id, o.commission_released_amount
  from orders o
  where o.id = any(p_order_ids) and o.commission_released_at is not null;

  if not exists (select 1 from tmp_unreleased_orders) then
    return '[]'::jsonb;
  end if;

  update orders o
  set commission_released_at = null,
      commission_released_by = null,
      commission_released_amount = null,
      commission_expense_id = null
  from tmp_unreleased_orders t
  where o.id = t.id;

  for v_expense_id in
    select distinct commission_expense_id from tmp_unreleased_orders where commission_expense_id is not null
  loop
    -- Check whether this expense would end up covering zero orders BEFORE writing anything --
    -- updating amount down to 0 first (then deleting) would trip expenses' `amount > 0` check
    -- constraint, since the update and the delete are separate statements.
    if coalesce((
      select array_length(
        array(select unnest(e.commission_order_ids) except select id from tmp_unreleased_orders), 1
      )
      from expenses e
      where e.id = v_expense_id
    ), 0) = 0 then
      delete from expenses where id = v_expense_id;
    else
      update expenses e
      set commission_order_ids = array(
            select unnest(e.commission_order_ids) except select id from tmp_unreleased_orders
          ),
          amount = e.amount - coalesce(
            (select sum(commission_released_amount) from tmp_unreleased_orders where commission_expense_id = v_expense_id), 0
          )
      where e.id = v_expense_id;
    end if;
  end loop;

  select array_agg(id) into v_unreleased_ids from tmp_unreleased_orders;
  return to_jsonb(v_unreleased_ids);
end;
$$;
