-- Payroll module: tracks one payroll "run" (a batch action, mirroring release_commission_orders'
-- shape) that pays out staff base salary as its own expense, separate from -- and never
-- double-counting -- the Commission module's own release mechanism.
create table if not exists payroll_runs (
  id uuid primary key default gen_random_uuid(),
  period_label text not null,
  period_start date not null,
  period_end date not null,
  created_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now(),
  check (period_end >= period_start)
);

-- One row per staff member included in a run. Kept separate from `expenses` (rather than a
-- staff_id column directly on expenses) so a run's roster/amounts can be read without assuming a
-- 1:1 expense-per-staff shape forever, and so a future partial-undo (out of scope for v1) has
-- somewhere to hang off. staff_id is set-null on user deletion, same as orders.layout_by /
-- commission_released_by -- deleting a staff account later must not silently delete payroll
-- history, only anonymize whose it was.
create table if not exists payroll_run_entries (
  id uuid primary key default gen_random_uuid(),
  payroll_run_id uuid not null references payroll_runs(id) on delete cascade,
  staff_id uuid references users(id) on delete set null,
  amount numeric(10,2) not null check (amount > 0),
  expense_id uuid references expenses(id) on delete set null,
  created_at timestamptz not null default now(),
  unique (payroll_run_id, staff_id)
);

create index if not exists idx_payroll_run_entries_run on payroll_run_entries (payroll_run_id);
create index if not exists idx_payroll_run_entries_staff on payroll_run_entries (staff_id);

alter table payroll_runs enable row level security;
alter table payroll_run_entries enable row level security;
-- No policies -- default-deny for the anon/authenticated Data API, same as every other table.
-- The Express server uses the service_role key, which bypasses RLS.

-- Marks an expense as auto-generated by a payroll run. Cascade (not set-null): v1 has no
-- partial-undo for a run -- deleting the run removes payroll_run_entries via its own cascade, and
-- this FK removes every expense the run created in the same statement. This is a v1 limitation:
-- unlike commission's per-order unrelease, there is no way to remove one staff member from an
-- already-created run without deleting the whole run and recreating it.
alter table expenses add column if not exists payroll_run_id uuid references payroll_runs(id) on delete cascade;

create index if not exists idx_expenses_payroll_run on expenses (payroll_run_id) where payroll_run_id is not null;

-- list_expenses(): return payroll_run_id alongside commission_order_ids so the frontend can
-- extend the same Auto badge / locked-fields treatment to payroll-generated expenses. Parameter
-- list unchanged -- pure row-shape addition, same pattern as commission_order_ids' own addition.
create or replace function list_expenses(
  p_search text default null,
  p_category text default null,
  p_payment_method text default null,
  p_date_from date default null,
  p_date_to date default null,
  p_created_by uuid default null,
  p_limit int default 10,
  p_offset int default 0,
  p_sort_by text default 'date',
  p_sort_dir text default 'desc'
)
returns jsonb
language sql
stable
as $$
  with filtered as (
    select e.*
    from expenses e
    where
      (p_search is null or p_search = '' or
        e.notes ilike '%' || p_search || '%' or
        e.category ilike '%' || p_search || '%')
      and (p_category is null or p_category = '' or e.category = p_category)
      and (p_payment_method is null or p_payment_method = '' or e.payment_method = p_payment_method)
      and (p_date_from is null or e.date >= p_date_from)
      and (p_date_to is null or e.date <= p_date_to)
      and (p_created_by is null or e.created_by = p_created_by)
  ),
  sorted as (
    select
      f.*,
      case p_sort_by when 'category' then f.category end as sort_text,
      case p_sort_by when 'amount' then f.amount end as sort_num
    from filtered f
  ),
  paged as (
    select *
    from sorted
    order by
      case when p_sort_dir = 'asc' then sort_text end asc,
      case when p_sort_dir = 'desc' then sort_text end desc,
      case when p_sort_dir = 'asc' then sort_num end asc,
      case when p_sort_dir = 'desc' then sort_num end desc,
      case when p_sort_by = 'date' and p_sort_dir = 'asc' then date end asc,
      case when p_sort_by = 'date' and p_sort_dir = 'desc' then date end desc,
      case when p_sort_by = 'created_at' and p_sort_dir = 'asc' then created_at end asc,
      case when p_sort_by = 'created_at' and p_sort_dir = 'desc' then created_at end desc,
      date desc,
      created_at desc
    limit p_limit offset p_offset
  )
  select jsonb_build_object(
    'rows', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', p.id,
        'date', p.date,
        'amount', p.amount,
        'category', p.category,
        'payment_method', p.payment_method,
        'notes', p.notes,
        'created_by', p.created_by,
        'created_by_name', coalesce(nullif(trim(coalesce(u.first_name, '') || ' ' || coalesce(u.last_name, '')), ''), ''),
        'recurring_expense_id', p.recurring_expense_id,
        'commission_order_ids', p.commission_order_ids,
        'payroll_run_id', p.payroll_run_id,
        'created_at', p.created_at,
        'updated_at', p.updated_at
      ) order by
        case when p_sort_dir = 'asc' then p.sort_text end asc,
        case when p_sort_dir = 'desc' then p.sort_text end desc,
        case when p_sort_dir = 'asc' then p.sort_num end asc,
        case when p_sort_dir = 'desc' then p.sort_num end desc,
        case when p_sort_by = 'date' and p_sort_dir = 'asc' then p.date end asc,
        case when p_sort_by = 'date' and p_sort_dir = 'desc' then p.date end desc,
        case when p_sort_by = 'created_at' and p_sort_dir = 'asc' then p.created_at end asc,
        case when p_sort_by = 'created_at' and p_sort_dir = 'desc' then p.created_at end desc,
        p.date desc,
        p.created_at desc)
      from paged p
      left join users u on u.id = p.created_by
    ), '[]'::jsonb),
    'total', (select count(*) from filtered)
  );
$$;

-- get_payroll_run(): one run's header + its staff entries, camelCase keys built directly in SQL
-- (matches commission_summary / list_commission_orders' convention). Returns null if the run
-- doesn't exist, so the caller can 404.
create or replace function get_payroll_run(p_run_id uuid)
returns jsonb
language sql
stable
as $$
  select case when r.id is null then null else jsonb_build_object(
    'id', r.id,
    'periodLabel', r.period_label,
    'periodStart', r.period_start,
    'periodEnd', r.period_end,
    'createdBy', r.created_by,
    'createdByName', coalesce(nullif(trim(coalesce(cu.first_name, '') || ' ' || coalesce(cu.last_name, '')), ''), ''),
    'createdAt', r.created_at,
    'totalAmount', coalesce((select sum(e.amount) from payroll_run_entries e where e.payroll_run_id = r.id), 0),
    'entries', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', e.id,
        'staffId', e.staff_id,
        'staffName', coalesce(nullif(trim(coalesce(su.first_name, '') || ' ' || coalesce(su.last_name, '')), ''), '(deleted user)'),
        'amount', e.amount,
        'expenseId', e.expense_id
      ) order by su.first_name, su.last_name)
      from payroll_run_entries e
      left join users su on su.id = e.staff_id
      where e.payroll_run_id = r.id
    ), '[]'::jsonb)
  ) end
  from payroll_runs r
  left join users cu on cu.id = r.created_by
  where r.id = p_run_id;
$$;

-- list_payroll_runs(): paginated run history, camelCase keys (same convention as
-- get_payroll_run). p_staff_id scopes to runs a given staff member was actually paid in (via
-- payroll_run_entries), independent of who created the run -- lets the route force a staff
-- caller to "their own history" without exposing every run's existence to them.
create or replace function list_payroll_runs(
  p_staff_id uuid default null,
  p_limit int default 20,
  p_offset int default 0
)
returns jsonb
language sql
stable
as $$
  with scoped as (
    select r.*
    from payroll_runs r
    where p_staff_id is null or exists (
      select 1 from payroll_run_entries e where e.payroll_run_id = r.id and e.staff_id = p_staff_id
    )
  ),
  paged as (
    select * from scoped order by created_at desc, id desc limit p_limit offset p_offset
  )
  select jsonb_build_object(
    'rows', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', p.id,
        'periodLabel', p.period_label,
        'periodStart', p.period_start,
        'periodEnd', p.period_end,
        'createdBy', p.created_by,
        'createdByName', coalesce(nullif(trim(coalesce(cu.first_name, '') || ' ' || coalesce(cu.last_name, '')), ''), ''),
        'createdAt', p.created_at,
        'staffCount', (select count(*) from payroll_run_entries e where e.payroll_run_id = p.id),
        'totalAmount', coalesce((select sum(e.amount) from payroll_run_entries e where e.payroll_run_id = p.id), 0)
      ) order by p.created_at desc, p.id desc)
      from paged p
      left join users cu on cu.id = p.created_by
    ), '[]'::jsonb),
    'total', (select count(*) from scoped)
  );
$$;

-- create_payroll_run(): atomically creates one payroll_runs row plus one expense and one
-- payroll_run_entries row per {staffId, amount} entry -- the same "multi-row, multi-table atomic
-- batch write" shape that pushed release_commission_orders to plpgsql instead of a
-- client-orchestrated sequence. Each entry's amount is whatever the caller sends (the admin's
-- possibly-edited per-run figure, already validated by the route layer) -- NOT re-derived from
-- users.salary_amount here, so an admin can deliberately pay someone a different amount for a
-- specific run without that requiring a users.salary_amount edit, and so a later salary_amount
-- change never retroactively touches an already-created run's expense (same live-vs-snapshot
-- split as commission_released_amount). p_entries shape:
-- [{"staffId": "<uuid>", "amount": <numeric>}, ...]. Unlike release_commission_orders' idempotent
-- silent-skip behavior, this RAISES (rolling back the whole run) on a malformed entry, an unknown
-- staffId, a non-positive amount, or a duplicate staffId -- a payroll run is a one-shot admin
-- action submitted fresh each time, not a repeatable batch over possibly-already-processed rows,
-- so there's no legitimate "partial resubmit" case to tolerate silently the way commission
-- release/unrelease does.
create or replace function create_payroll_run(
  p_period_label text,
  p_period_start date,
  p_period_end date,
  p_entries jsonb,
  p_actor_id uuid
)
returns jsonb
language plpgsql
as $$
declare
  v_run_id uuid;
  v_entry jsonb;
  v_staff_id uuid;
  v_amount numeric(10,2);
  v_staff_name text;
  v_expense_id uuid;
begin
  if p_entries is null or jsonb_typeof(p_entries) <> 'array' or jsonb_array_length(p_entries) = 0 then
    raise exception 'p_entries must be a non-empty array';
  end if;

  insert into payroll_runs (period_label, period_start, period_end, created_by)
  values (p_period_label, p_period_start, p_period_end, p_actor_id)
  returning id into v_run_id;

  for v_entry in select * from jsonb_array_elements(p_entries)
  loop
    v_staff_id := (v_entry->>'staffId')::uuid;
    v_amount := (v_entry->>'amount')::numeric(10,2);

    if v_staff_id is null or v_amount is null or v_amount <= 0 then
      raise exception 'each entry requires a staffId and an amount greater than 0';
    end if;

    select trim(coalesce(first_name, '') || ' ' || coalesce(last_name, '')) into v_staff_name
    from users where id = v_staff_id;
    if v_staff_name is null then
      raise exception 'staff member % not found', v_staff_id;
    end if;

    insert into expenses (id, date, amount, category, payment_method, notes, created_by, payroll_run_id)
    values (
      gen_random_uuid(),
      current_date,
      v_amount,
      'Payroll and Employee Costs',
      'Cash',
      'Payroll — ' || v_staff_name || ' (' || p_period_label || ')',
      p_actor_id,
      v_run_id
    )
    returning id into v_expense_id;

    -- Duplicate staffId in p_entries trips the payroll_run_entries (payroll_run_id, staff_id)
    -- unique constraint here, raising and rolling back the whole function -- deliberately not
    -- deduped/merged, since a duplicate almost certainly indicates a client bug.
    insert into payroll_run_entries (payroll_run_id, staff_id, amount, expense_id)
    values (v_run_id, v_staff_id, v_amount, v_expense_id);
  end loop;

  return get_payroll_run(v_run_id);
end;
$$;
