-- Release mechanism for the monthly incentive pool (mirrors the per-order commission
-- release/unrelease mechanism in 20260910170000_add_order_commission_release.sql and
-- 20260910190000_add_commission_release_expense.sql, adapted to a team-wide monthly total
-- instead of per-order amounts).
--
-- Unlike per-order commission, the monthly incentive isn't a column on an existing row -- it's an
-- aggregate computed from a whole month of orders. Releasing it therefore needs its own row to
-- mark "this calendar month has been paid out" (one release per period_month, enforced by the
-- unique constraint) plus a locked-in snapshot of the totals and the per-staff split at release
-- time, so a later order edit/cancellation can't silently change what was already paid out --
-- the same reasoning as orders.commission_released_amount.
create table if not exists monthly_incentive_releases (
  id uuid primary key default gen_random_uuid(),
  period_month date not null unique,
  total_staff_sales numeric(12, 2) not null,
  pool numeric(10, 2) not null,
  released_at timestamptz not null default now(),
  released_by uuid references users(id) on delete set null,
  created_at timestamptz not null default now()
);

create table if not exists monthly_incentive_release_shares (
  id uuid primary key default gen_random_uuid(),
  release_id uuid not null references monthly_incentive_releases(id) on delete cascade,
  user_id uuid references users(id) on delete set null,
  own_sales numeric(12, 2) not null,
  percentage_share numeric(7, 4) not null,
  commission_share numeric(10, 2) not null,
  expense_id uuid references expenses(id) on delete set null
);

create index if not exists monthly_incentive_release_shares_release_id_idx
  on monthly_incentive_release_shares (release_id);

alter table monthly_incentive_releases enable row level security;
alter table monthly_incentive_release_shares enable row level security;
-- No policies: default-deny for anon/authenticated via the Data API.
-- The Express server uses the service_role key, which bypasses RLS.

-- Marks an expense as auto-generated by a monthly incentive release, and which release it came
-- from -- same "marker column" convention as expenses.commission_order_ids, giving this feature
-- its own ExpenseAutoSource without touching the existing commission-release marker.
alter table expenses add column if not exists monthly_incentive_release_id uuid
  references monthly_incentive_releases(id) on delete set null;

-- list_expenses(): surface the new marker alongside commission_order_ids so the frontend can lock
-- Amount/Category/Date and disable Delete for these rows too, same convention as the commission
-- release marker's addition.
create or replace function list_expenses(
  p_search text default null,
  p_category text default null,
  p_payment_method text default null,
  p_date_from date default null,
  p_date_to date default null,
  p_created_by uuid default null,
  p_limit int default 10,
  p_offset int default 0,
  p_sort_by text default 'date',
  p_sort_dir text default 'desc'
)
returns jsonb
language sql
stable
as $$
  with filtered as (
    select e.*
    from expenses e
    where
      (p_search is null or p_search = '' or
        e.notes ilike '%' || p_search || '%' or
        e.category ilike '%' || p_search || '%')
      and (p_category is null or p_category = '' or e.category = p_category)
      and (p_payment_method is null or p_payment_method = '' or e.payment_method = p_payment_method)
      and (p_date_from is null or e.date >= p_date_from)
      and (p_date_to is null or e.date <= p_date_to)
      and (p_created_by is null or e.created_by = p_created_by)
  ),
  sorted as (
    select
      f.*,
      case p_sort_by when 'category' then f.category end as sort_text,
      case p_sort_by when 'amount' then f.amount end as sort_num
    from filtered f
  ),
  paged as (
    select *
    from sorted
    order by
      case when p_sort_dir = 'asc' then sort_text end asc,
      case when p_sort_dir = 'desc' then sort_text end desc,
      case when p_sort_dir = 'asc' then sort_num end asc,
      case when p_sort_dir = 'desc' then sort_num end desc,
      case when p_sort_by = 'date' and p_sort_dir = 'asc' then date end asc,
      case when p_sort_by = 'date' and p_sort_dir = 'desc' then date end desc,
      case when p_sort_by = 'created_at' and p_sort_dir = 'asc' then created_at end asc,
      case when p_sort_by = 'created_at' and p_sort_dir = 'desc' then created_at end desc,
      date desc,
      created_at desc
    limit p_limit offset p_offset
  )
  select jsonb_build_object(
    'rows', coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', p.id,
        'date', p.date,
        'amount', p.amount,
        'category', p.category,
        'payment_method', p.payment_method,
        'notes', p.notes,
        'created_by', p.created_by,
        'created_by_name', coalesce(nullif(trim(coalesce(u.first_name, '') || ' ' || coalesce(u.last_name, '')), ''), ''),
        'recurring_expense_id', p.recurring_expense_id,
        'commission_order_ids', p.commission_order_ids,
        'monthly_incentive_release_id', p.monthly_incentive_release_id,
        'created_at', p.created_at,
        'updated_at', p.updated_at
      ) order by
        case when p_sort_dir = 'asc' then p.sort_text end asc,
        case when p_sort_dir = 'desc' then p.sort_text end desc,
        case when p_sort_dir = 'asc' then p.sort_num end asc,
        case when p_sort_dir = 'desc' then p.sort_num end desc,
        case when p_sort_by = 'date' and p_sort_dir = 'asc' then p.date end asc,
        case when p_sort_by = 'date' and p_sort_dir = 'desc' then p.date end desc,
        case when p_sort_by = 'created_at' and p_sort_dir = 'asc' then p.created_at end asc,
        case when p_sort_by = 'created_at' and p_sort_dir = 'desc' then p.created_at end desc,
        p.date desc,
        p.created_at desc)
      from paged p
      left join users u on u.id = p.created_by
    ), '[]'::jsonb),
    'total', (select count(*) from filtered)
  );
$$;

-- Shared by monthly_commission_tier_summary/release_monthly_incentive so the staff-sales
-- eligibility rule (staff-role creator, paid, non-cancelled/refunded/returned, in range) lives in
-- exactly one place. Returns one row per staff member with at least one eligible order --
-- unlike commission_summary's per-order join, there's no per-row payment_status split here since
-- only 'paid' orders are eligible at all for this feature.
create or replace function monthly_incentive_staff_sales(p_date_from date, p_date_to date)
returns table(created_by uuid, own_sales numeric)
language sql
stable
as $$
  select o.created_by, sum(o.total) as own_sales
  from orders o
  join users u on u.id = o.created_by
  where u.role = 'staff'
    and o.payment_status = 'paid'
    and o.status not in ('cancelled', 'refunded', 'returned')
    and o.created_at >= p_date_from::timestamptz
    and o.created_at < (p_date_to + 1)::timestamptz
  group by o.created_by;
$$;

-- monthly_commission_tier_summary(): now release-aware. When the requested period's calendar
-- month has already been released (a row exists in monthly_incentive_releases for that month),
-- totalStaffSales/pool/perStaff come from the locked-in snapshot instead of a live recompute --
-- same live-vs-snapshot convention as commission_summary()'s released orders. The 9-tier ladder
-- itself is still recomputed against the (possibly snapshotted) total, since the ladder's
-- thresholds/amounts are constants, not something that needs freezing.
create or replace function monthly_commission_tier_summary(
  p_date_from date,
  p_date_to date
)
returns jsonb
language sql
stable
as $$
  with period_month as (
    select date_trunc('month', p_date_from::timestamptz)::date as month
  ),
  release_row as (
    select r.*
    from monthly_incentive_releases r, period_month pm
    where r.period_month = pm.month
  ),
  tiers(threshold, amount) as (
    values
      (100000::numeric, 2000::numeric),
      (150000::numeric, 2500::numeric),
      (200000::numeric, 3000::numeric),
      (250000::numeric, 3500::numeric),
      (300000::numeric, 4000::numeric),
      (350000::numeric, 4500::numeric),
      (400000::numeric, 5000::numeric),
      (450000::numeric, 5500::numeric),
      (500000::numeric, 6000::numeric)
  ),
  live_per_staff as (
    select * from monthly_incentive_staff_sales(p_date_from, p_date_to)
  ),
  live_totals as (
    select coalesce(sum(own_sales), 0) as total_staff_sales from live_per_staff
  ),
  live_pool_calc as (
    select coalesce(
      (
        select t.amount
        from tiers t, live_totals lt
        where lt.total_staff_sales >= t.threshold
        order by t.threshold desc
        limit 1
      ),
      0
    ) as pool
  ),
  effective as (
    select
      coalesce(rr.total_staff_sales, lt.total_staff_sales) as total_staff_sales,
      coalesce(rr.pool, pc.pool) as pool,
      rr.id as release_id,
      rr.released_at,
      rr.released_by
    from live_totals lt, live_pool_calc pc
    left join release_row rr on true
  ),
  tier_rows as (
    select
      t.threshold,
      t.amount,
      least(e.total_staff_sales / t.threshold, 1) * 100 as progress_percent,
      e.total_staff_sales >= t.threshold as is_met
    from tiers t, effective e
  ),
  live_staff_rows as (
    select
      lps.created_by,
      lps.own_sales,
      case when lt.total_staff_sales > 0 then lps.own_sales / lt.total_staff_sales * 100 else 0 end
        as percentage_share,
      case when lt.total_staff_sales > 0 then lps.own_sales / lt.total_staff_sales * pc.pool else 0 end
        as commission_share
    from live_per_staff lps, live_totals lt, live_pool_calc pc
  ),
  released_staff_rows as (
    select s.user_id as created_by, s.own_sales, s.percentage_share, s.commission_share
    from monthly_incentive_release_shares s
    join release_row rr on rr.id = s.release_id
  )
  select jsonb_build_object(
    'totalStaffSales', e.total_staff_sales,
    'pool', e.pool,
    'tiers', (
      select coalesce(jsonb_agg(
        jsonb_build_object(
          'threshold', tr.threshold,
          'amount', tr.amount,
          'progressPercent', tr.progress_percent,
          'isMet', tr.is_met
        ) order by tr.threshold asc
      ), '[]'::jsonb)
      from tier_rows tr
    ),
    'perStaff', (
      case when e.release_id is not null then (
        select coalesce(jsonb_agg(
          jsonb_build_object(
            'userId', rsr.created_by,
            'name', coalesce(nullif(trim(coalesce(u.first_name, '') || ' ' || coalesce(u.last_name, '')), ''), ''),
            'ownSales', rsr.own_sales,
            'percentageShare', rsr.percentage_share,
            'commissionShare', rsr.commission_share
          ) order by rsr.own_sales desc
        ), '[]'::jsonb)
        from released_staff_rows rsr
        left join users u on u.id = rsr.created_by
      )
      else (
        select coalesce(jsonb_agg(
          jsonb_build_object(
            'userId', lsr.created_by,
            'name', coalesce(nullif(trim(coalesce(u.first_name, '') || ' ' || coalesce(u.last_name, '')), ''), ''),
            'ownSales', lsr.own_sales,
            'percentageShare', lsr.percentage_share,
            'commissionShare', lsr.commission_share
          ) order by lsr.own_sales desc
        ), '[]'::jsonb)
        from live_staff_rows lsr
        join users u on u.id = lsr.created_by
      )
    end
    ),
    'releasedAt', e.released_at,
    'releasedBy', e.released_by,
    'releasedByName', (
      select coalesce(nullif(trim(coalesce(u2.first_name, '') || ' ' || coalesce(u2.last_name, '')), ''), '')
      from users u2
      where u2.id = e.released_by
    )
  )
  from effective e;
$$;

-- Releases the monthly incentive pool for the calendar month containing p_date_from: snapshots
-- the current total staff sales and per-staff split, creates one expense per staff member
-- (category 'Payroll and Employee Costs', same convention as release_commission_orders), and
-- records the release so monthly_commission_tier_summary switches that month to the frozen
-- snapshot. Raises if the month was already released (one release per month, not a re-stampable
-- batch like per-order release) or if no tier has been unlocked yet (nothing to release).
create or replace function release_monthly_incentive(p_date_from date, p_date_to date, p_actor_id uuid)
returns jsonb
language plpgsql
as $$
declare
  v_period_month date := date_trunc('month', p_date_from::timestamptz)::date;
  v_release_id uuid;
  v_total_staff_sales numeric;
  v_pool numeric;
  v_expense_id uuid;
  v_staff record;
begin
  if exists (select 1 from monthly_incentive_releases where period_month = v_period_month) then
    raise exception 'The monthly incentive for this period has already been released.';
  end if;

  select coalesce(sum(own_sales), 0) into v_total_staff_sales
  from monthly_incentive_staff_sales(p_date_from, p_date_to);

  select coalesce(
    (
      select amount
      from (values
        (100000::numeric, 2000::numeric), (150000::numeric, 2500::numeric), (200000::numeric, 3000::numeric),
        (250000::numeric, 3500::numeric), (300000::numeric, 4000::numeric), (350000::numeric, 4500::numeric),
        (400000::numeric, 5000::numeric), (450000::numeric, 5500::numeric), (500000::numeric, 6000::numeric)
      ) as t(threshold, amount)
      where v_total_staff_sales >= threshold
      order by threshold desc
      limit 1
    ),
    0
  ) into v_pool;

  if v_pool <= 0 then
    raise exception 'No incentive tier has been unlocked for this period yet.';
  end if;

  insert into monthly_incentive_releases (period_month, total_staff_sales, pool, released_by)
  values (v_period_month, v_total_staff_sales, v_pool, p_actor_id)
  returning id into v_release_id;

  for v_staff in
    select
      s.created_by,
      s.own_sales,
      s.own_sales / v_total_staff_sales * 100 as percentage_share,
      s.own_sales / v_total_staff_sales * v_pool as commission_share
    from monthly_incentive_staff_sales(p_date_from, p_date_to) s
  loop
    insert into expenses (id, date, amount, category, payment_method, notes, created_by, monthly_incentive_release_id)
    values (
      gen_random_uuid(),
      current_date,
      v_staff.commission_share,
      'Payroll and Employee Costs',
      'Cash',
      'Monthly incentive — '
        || (select trim(coalesce(first_name, '') || ' ' || coalesce(last_name, '')) from users where id = v_staff.created_by)
        || ' (' || to_char(v_period_month, 'FMMonth YYYY') || ')',
      p_actor_id,
      v_release_id
    )
    returning id into v_expense_id;

    insert into monthly_incentive_release_shares (
      release_id, user_id, own_sales, percentage_share, commission_share, expense_id
    ) values (
      v_release_id, v_staff.created_by, v_staff.own_sales, v_staff.percentage_share, v_staff.commission_share, v_expense_id
    );
  end loop;

  return jsonb_build_object('releaseId', v_release_id, 'periodMonth', v_period_month);
end;
$$;

-- Reverses release_monthly_incentive: deletes the expenses it created (one per staff member) and
-- the release/share rows, so monthly_commission_tier_summary falls back to a live recompute for
-- that month. No-op (returns unreleased: false) if the month was never released.
create or replace function unrelease_monthly_incentive(p_date_from date, p_date_to date)
returns jsonb
language plpgsql
as $$
declare
  v_period_month date := date_trunc('month', p_date_from::timestamptz)::date;
  v_release_id uuid;
begin
  select id into v_release_id from monthly_incentive_releases where period_month = v_period_month;

  if v_release_id is null then
    return jsonb_build_object('unreleased', false);
  end if;

  delete from expenses
  where id in (
    select expense_id from monthly_incentive_release_shares
    where release_id = v_release_id and expense_id is not null
  );

  delete from monthly_incentive_releases where id = v_release_id;

  return jsonb_build_object('unreleased', true, 'periodMonth', v_period_month);
end;
$$;
